name: Matrix

on:
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Generate data
        id: matrix
        run: |
          cat << EOF > data.json
          [
            {
              "color": "red",
              "value": "#f00"
            },
            {
              "color": "green",
              "value": "#0f0"
            },
            {
              "color": "blue",
              "value": "#00f"
            },
            {
              "color": "cyan",
              "value": "#0ff"
            }
          ]
          EOF

          # We got this data, but our team needs some post-processing done, in this example let's remove cyan
          OUTPUT=$(jq 'del(.[] | select(.color == "cyan"))' data.json)
          echo $OUTPUT

          # Let's now add in the "include" piece of the JSON to define the matrix to fully construct our matrix
          MATRIX_OUTPUT=$(echo "{\"include\":$OUTPUT}")
          echo $MATRIX_OUTPUT

          echo matrix=$MATRIX_OUTPUT >> $GITHUB_OUTPUT

  run-matrix:
    runs-on: ubuntu-latest
    needs:
      - generate-matrix
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Print
        run: echo "The Color ${{ matrix.text_color }} is Hex ${{ matrix.hex_color }}.
