name: Repository Dispatch - Listener

on:
  repository_dispatch:
    types:
      - trigger-one
      - trigger-two

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get date
        run: echo ${{ github.event.client_payload.date }}

      - name: check sha from first trigger
        if: github.event.event_type == "trigger-one"
        run: echo ${{ github.event.client_payload.commit-sha }}